### ISSUE TITLE
Example mmol.mL-1 links to the wrong place

### ISSUE THREAD

**Issue by dr-shorthair** [units-of-measurement/units-of-measurement-server#9]
The link from the list of examples on https://units-of-measurement.org/ goes to https://units-of-measurement.org/mmol.mL-2

**Comment by kaiiam** [comment]
@dr-shorthair that behavior isn't happening for me. Do you mind checking again?

**Comment by jamesaoverton** [comment]
He's referring to the example link on the home page, which does contain this error.

**Comment by jamesaoverton** [comment]
Fixed now!
